services:
  transcribe:
    image: transcribe:prod
    pull_policy: never
    container_name: transcribe
    mem_limit: 1g
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '20m'
        max-file: '5'
        compress: 'true'
    networks:
      - my_network
    env_file:
      - .env
    labels:
      diun.enable: 'false'
    build:
      context: .
      dockerfile: Dockerfile
