#!/usr/bin/env node
/**
 * build-locale.mjs — Build per-language .ini files + manifest
 *
 * Previously this merged ALL locales into one public/data.ini (~100KB),
 * so every user downloaded every language regardless of which one they
 * needed. Now each language gets its own small file:
 *
 *   public/locales/{code}.ini        — e.g. public/locales/pl.ini
 *   public/locales/manifest.json     — list of available language codes
 *   src/l10n/generated/defaultLocale.ts
 *     → inlines en-US into the JS bundle, so the default language needs
 *       ZERO network requests (no flash of raw keys on first load).
 *
 * Run: node scripts/build-locale.mjs
 */

import fs from 'node:fs';
import path from 'node:path';

const __dirname = import.meta.dirname;
const L10N_DIR = path.resolve(__dirname, '../src/l10n');
const OUT_DIR = path.resolve(__dirname, '../public/locales');
const GENERATED_DIR = path.resolve(__dirname, '../src/l10n/generated');
const DEFAULT_LANG = 'en-US';

// Map filename → BCP-47 language code used as [section] header in the
// per-language output file (kept identical to the old combined format,
// so iniParser.ts's parseIni(content, langCode) needs no changes).
const FILE_MAP = {
  '_english.ini': 'en-US',
  'arabic.ini': 'ar',
  'catalan.ini': 'ca',
  'chinese-simplified.ini': 'zh-CN',
  'chinese-traditional.ini': 'zh-TW',
  'danish.ini': 'da',
  'dutch.ini': 'nl',
  'filipino.ini': 'fil',
  'french.ini': 'fr',
  'german.ini': 'de',
  'greek.ini': 'el',
  'hindi.ini': 'hi',
  'indonesian.ini': 'id',
  'italian.ini': 'it',
  'japanese.ini': 'ja',
  'marathi.ini': 'mr',
  'norwegian.ini': 'no',
  'polish.ini': 'pl',
  'portuguese-br.ini': 'pt-BR',
  'portuguese.ini': 'pt',
  'romanian.ini': 'ro',
  'russian.ini': 'ru',
  'spanish.ini': 'es',
  'swedish.ini': 'sv',
  'tibetan.ini': 'bo',
  'turkish.ini': 'tr',
  'ukrainian.ini': 'uk',
  'vietnamese.ini': 'vi',
};

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.mkdirSync(GENERATED_DIR, { recursive: true });

const manifest = [];
let defaultLocaleContent = null;
let totalBytes = 0;

for (const [filename, langCode] of Object.entries(FILE_MAP)) {
  const filePath = path.join(L10N_DIR, filename);
  if (!fs.existsSync(filePath)) {
    console.warn(`[build-locale] Missing: ${filename}`);
    continue;
  }

  let content = fs.readFileSync(filePath, 'utf8');

  // Replace the original [lang] section header with the BCP-47 code.
  content = content.replace(/^\[[^\]]+\]/m, `[${langCode}]`);
  content = content.trim() + '\n';

  const outFile = path.join(OUT_DIR, `${langCode}.ini`);
  fs.writeFileSync(outFile, content, 'utf8');

  const bytes = Buffer.byteLength(content, 'utf8');
  totalBytes += bytes;
  manifest.push(langCode);

  if (langCode === DEFAULT_LANG) {
    defaultLocaleContent = content;
  }

  console.log(
    `[build-locale] ✓ ${filename} → locales/${langCode}.ini (${(bytes / 1024).toFixed(1)} KB)`,
  );
}

// Manifest — lets the app list available languages (e.g. in a settings
// dropdown) without fetching every single locale file just to find out
// what exists.
fs.writeFileSync(
  path.join(OUT_DIR, 'manifest.json'),
  JSON.stringify(manifest, null, 2),
  'utf8',
);

if (!defaultLocaleContent) {
  throw new Error(
    `[build-locale] Default language "${DEFAULT_LANG}" not found — cannot generate defaultLocale.ts`,
  );
}

// Inline the default language into the JS bundle. This means:
//  - first-time visitors see correct text immediately, no fetch, no
//    flash of raw i18n keys while /locales/en-US.ini downloads
//  - it also acts as the always-available fallback source for missing
//    keys in every other language (see I18nContext.tsx)
const generatedModule = `/**
 * AUTO-GENERATED by scripts/build-locale.mjs — do not edit directly.
 * Inlines the ${DEFAULT_LANG} locale into the JS bundle so the app has
 * a translation source with zero network round-trip on first paint.
 */
export const DEFAULT_LANG = ${JSON.stringify(DEFAULT_LANG)};
export const DEFAULT_LOCALE_INI = ${JSON.stringify(defaultLocaleContent)};
`;

fs.writeFileSync(
  path.join(GENERATED_DIR, 'defaultLocale.ts'),
  generatedModule,
  'utf8',
);

console.log(
  `\n[build-locale] Written ${manifest.length} locale files to ${OUT_DIR}`,
);
console.log(
  `[build-locale] Combined size across all languages: ${(totalBytes / 1024).toFixed(1)} KB total, ` +
    `but each visitor now only ever downloads their own language ` +
    `(~${(totalBytes / manifest.length / 1024).toFixed(1)} KB avg) — and en-US visitors download 0 KB, since it's inlined in the JS bundle.`,
);
